{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# This notebook handles ingestion of stocks data to feature store"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> 2022-05-23 10:55:46,515 [info] loaded project stocks from MLRun DB\n"
     ]
    }
   ],
   "source": [
    "import mlrun\n",
    "project = mlrun.get_or_create_project(name='stocks',user_project=True, context=\"./\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> <b> Steps </b>\n",
    "> * [Creating mlrun function that reads stocks from yahoo_fin and returning record oriented json](#Creating-mlrun-function-that-reads-stocks-from-yahoo_fin-and-returning-record-oriented-json)\n",
    "> * [Creating a feature set and declaring the graph](#Creating-a-feature-set-and-declaring-the-graph)\n",
    "> * [Dummy ingestion, Deploying ingestion service and getting ingestion endpoint](#Dummy-ingestion,-Deploying-ingestion-service-and-getting-ingestion-endpoint)\n",
    "> * [Testing ingestion service](#Testing-ingestion-service)\n",
    "> * [Creating scheduled mlrun job to invoke our function every time delta](#Creating-scheduled-mlrun-job-to-invoke-our-function-every-time-delta)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Creating mlrun function that reads stocks from yahoo_fin and returning record oriented json\n",
    "similar to ingest_stocks, we collect the data from within the feature-set graph. <br>\n",
    "event sent to graph is real-time configuration."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "STREAM_SHARDS = 1 # NO. of input stream shard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# serving function configuration\n",
    "SERVING_FUNCTION_RESPONSE = 'SYNC'\n",
    "MIN_REPLICAS = 1 # serving function minimum replicas\n",
    "MAX_REPLICAS = 1 # serving function maximum replicas\n",
    "SERVING_PROCESSING_TIME = 1 # time for the serving function to sleep\n",
    "WORKER_AVAILIBALITY_TIMEOUT = 100\n",
    "INGRESS_TIMEOUT = 150\n",
    "USE_GPU = False # whether the serving function will use GPU (if true - REMOTE_SCALE_RANGE will determine the consumption)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# RemoteStep configuration\n",
    "REMOTE_STEP_WORKERS = 1\n",
    "MAX_IN_FLIGHT = 1  # how many simulteneous events on each worker in the serving function\n",
    "REMOTE_STEP_HTTP_TIMEOUT = 150\n",
    "STOREY_QUEUE_SIZE = 8\n",
    "WINDOW_ACK = (STOREY_QUEUE_SIZE+MAX_IN_FLIGHT)*STREAM_SHARDS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> 2022-05-23 10:55:51,226 [info] Starting remote function deploy\n",
      "2022-05-23 10:55:51  (info) Deploying function\n",
      "2022-05-23 10:55:51  (info) Building\n",
      "2022-05-23 10:55:51  (info) Staging files and preparing base images\n",
      "2022-05-23 10:55:51  (info) Building processor image\n",
      "2022-05-23 10:57:46  (info) Build complete\n",
      "2022-05-23 10:59:16  (info) Function deploy complete\n",
      "> 2022-05-23 10:59:17,574 [info] successfully deployed function: {'internal_invocation_urls': ['nuclio-stocks-avia-sentiment-analysis-serving.default-tenant.svc.cluster.local:8080'], 'external_invocation_urls': ['stocks-avia-sentiment-analysis-serving-stocks-avia.default-tenant.app.dev39.lab.iguazeng.com/']}\n"
     ]
    }
   ],
   "source": [
    "import nuclio\n",
    "import mlrun\n",
    "\n",
    "model_location = 'https://iguazio-sample-data.s3.amazonaws.com/models/model.pt'\n",
    "scaled_function = mlrun.import_function('hub://sentiment_analysis_serving')\n",
    "scaled_function.spec.min_replicas = MIN_REPLICAS\n",
    "scaled_function.spec.max_replicas = MAX_REPLICAS\n",
    "scaled_function.add_model('sentiment_analysis_model', model_path=model_location, class_name='SentimentClassifierServing')\n",
    "\n",
    "scaled_function.with_http(workers=REMOTE_STEP_WORKERS, gateway_timeout=INGRESS_TIMEOUT, worker_timeout=WORKER_AVAILIBALITY_TIMEOUT)\n",
    "\n",
    "env_vars = {\"SERVING_FUNCTION_TIME_TO_SLEEP\": SERVING_PROCESSING_TIME}\n",
    "\n",
    "scaled_function.set_envs(env_vars)\n",
    "scaled_function.spec.readiness_timeout = 300\n",
    "address = scaled_function.deploy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#mlrun: start-code\n",
    "\n",
    "import yahoo_fin.stock_info as si\n",
    "import yahoo_fin.news as ynews\n",
    "from dateutil import parser\n",
    "import pandas as pd \n",
    "import json\n",
    "import requests\n",
    "from storey import MapClass, Event\n",
    "import string\n",
    "import mlrun\n",
    "\n",
    "def remove_punctuation(text):\n",
    "    punctuationfree=\"\".join([i for i in text if i not in string.punctuation])\n",
    "    return punctuationfree\n",
    "\n",
    "def get_news(event):\n",
    "    '''\n",
    "    event: dict with the following keys:\n",
    "    n_stocks - how many stocks to collect\n",
    "    '''\n",
    "    tickers = si.tickers_sp500()[:event['n_stocks']]\n",
    "    tickers_news = []\n",
    "    for ticker in tickers:\n",
    "        news = ynews.get_yf_rss(ticker=ticker)\n",
    "        news_df = pd.DataFrame(news)\n",
    "        df_copy = news_df[['title','summary','link','published']].copy()\n",
    "        df_copy['ticker'] = ticker\n",
    "        df_copy['Datetime'] = df_copy['published'].apply(lambda x: parser.parse(x).strftime('%Y-%m-%d %H:%M:%S'))\n",
    "        df_copy['summary'] = df_copy['summary'].apply(lambda x:remove_punctuation(x))\n",
    "        df_copy['title'] = df_copy['title'].apply(lambda x:remove_punctuation(x))\n",
    "        tickers_news.append(df_copy)\n",
    "    df = pd.concat(tickers_news).reset_index(drop=True)\n",
    "    return json.loads(df.to_json(orient='records'))\n",
    "\n",
    "class sentiment_analysis(MapClass):\n",
    "    def __init__(self,**kwargs):\n",
    "        super().__init__(**kwargs)\n",
    "        model_location = 'https://iguazio-sample-data.s3.amazonaws.com/models/model.pt'\n",
    "        fn = mlrun.import_function('hub://sentiment_analysis_serving')\n",
    "        fn.add_model('sentiment_analysis_model', model_path=model_location, class_name='SentimentClassifierServing')\n",
    "        self.sentiment_model_endpoint = fn.deploy()\n",
    "        \n",
    "    def do(self,event):\n",
    "        event.body['sentiment'] = json.loads(requests.put(self.sentiment_model_endpoint + \"/v2/models/sentiment_analysis_model/predict\",\n",
    "                                                     json=json.dumps({'inputs':[event.body['summary']]})).text)['outputs'][0]/2 # so it'll be 0 for neg, 0.5 for neutral and 1 for pos\n",
    "        \n",
    "        return Event(event.body,key=event.body['ticker'],time=event.body['Datetime'])\n",
    "    \n",
    "#mlrun: end-code"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Creating a feature set and declaring the graph"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "fn = mlrun.import_function('hub://sentiment_analysis_serving')\n",
    "mod = mlrun.function_to_module(fn,workdir='./')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tmpvbd4574z.SentimentClassifierServing"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mod.SentimentClassifierServing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n",
       "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n",
       " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n",
       "<!-- Generated by graphviz version 2.40.1 (20161225.0304)\n",
       " -->\n",
       "<!-- Title: mlrun&#45;flow Pages: 1 -->\n",
       "<svg width=\"691pt\" height=\"98pt\"\n",
       " viewBox=\"0.00 0.00 690.76 98.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n",
       "<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 94)\">\n",
       "<title>mlrun&#45;flow</title>\n",
       "<polygon fill=\"#ffffff\" stroke=\"transparent\" points=\"-4,4 -4,-94 686.764,-94 686.764,4 -4,4\"/>\n",
       "<!-- _start -->\n",
       "<g id=\"node1\" class=\"node\">\n",
       "<title>_start</title>\n",
       "<polygon fill=\"#d3d3d3\" stroke=\"#000000\" points=\"38.5476,-27.0493 40.698,-27.1479 42.8263,-27.2953 44.9236,-27.4913 46.9815,-27.7353 48.9917,-28.0266 50.9463,-28.3645 52.8377,-28.7479 54.6587,-29.1759 56.4025,-29.6472 58.0628,-30.1606 59.634,-30.7147 61.1107,-31.308 62.4882,-31.9388 63.7625,-32.6054 64.9302,-33.3059 65.9882,-34.0385 66.9343,-34.8012 67.7669,-35.5918 68.4849,-36.4082 69.0878,-37.2481 69.5758,-38.1093 69.9496,-38.9894 70.2102,-39.886 70.3595,-40.7965 70.3997,-41.7186 70.3334,-42.6497 70.1636,-43.5873 69.8937,-44.5287 69.5276,-45.4713 69.0691,-46.4127 68.5225,-47.3503 67.8923,-48.2814 67.1831,-49.2035 66.3996,-50.114 65.5464,-51.0106 64.6285,-51.8907 63.6504,-52.7519 62.617,-53.5918 61.5329,-54.4082 60.4024,-55.1988 59.2299,-55.9615 58.0197,-56.6941 56.7755,-57.3946 55.5012,-58.0612 54.2002,-58.692 52.8757,-59.2853 51.5309,-59.8394 50.1684,-60.3528 48.7908,-60.8241 47.4003,-61.2521 45.9989,-61.6355 44.5886,-61.9734 43.1708,-62.2647 41.7472,-62.5087 40.3189,-62.7047 38.8872,-62.8521 37.4531,-62.9507 36.0175,-63 34.5815,-63 33.146,-62.9507 31.7119,-62.8521 30.2801,-62.7047 28.8519,-62.5087 27.4282,-62.2647 26.0105,-61.9734 24.6001,-61.6355 23.1988,-61.2521 21.8083,-60.8241 20.4306,-60.3528 19.0681,-59.8394 17.7233,-59.2853 16.3989,-58.692 15.0979,-58.0612 13.8236,-57.3946 12.5794,-56.6941 11.3691,-55.9615 10.1967,-55.1988 9.0662,-54.4082 7.982,-53.5918 6.9486,-52.7519 5.9706,-51.8907 5.0526,-51.0106 4.1995,-50.114 3.4159,-49.2035 2.7067,-48.2814 2.0765,-47.3503 1.53,-46.4127 1.0715,-45.4713 .7053,-44.5287 .4355,-43.5873 .2657,-42.6497 .1993,-41.7186 .2395,-40.7965 .3888,-39.886 .6495,-38.9894 1.0232,-38.1093 1.5112,-37.2481 2.1141,-36.4082 2.8321,-35.5918 3.6647,-34.8012 4.6109,-34.0385 5.6689,-33.3059 6.8365,-32.6054 8.1108,-31.9388 9.4884,-31.308 10.9651,-30.7147 12.5362,-30.1606 14.1966,-29.6472 15.9404,-29.1759 17.7614,-28.7479 19.6528,-28.3645 21.6074,-28.0266 23.6176,-27.7353 25.6755,-27.4913 27.7728,-27.2953 29.901,-27.1479 32.0515,-27.0493 34.2154,-27 36.3837,-27 38.5476,-27.0493\"/>\n",
       "<text text-anchor=\"middle\" x=\"35.2995\" y=\"-41.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">start</text>\n",
       "</g>\n",
       "<!-- get_news -->\n",
       "<g id=\"node2\" class=\"node\">\n",
       "<title>get_news</title>\n",
       "<ellipse fill=\"none\" stroke=\"#000000\" cx=\"161.1942\" cy=\"-45\" rx=\"54.6905\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"161.1942\" y=\"-41.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">get_news</text>\n",
       "</g>\n",
       "<!-- _start&#45;&gt;get_news -->\n",
       "<g id=\"edge1\" class=\"edge\">\n",
       "<title>_start&#45;&gt;get_news</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M70.0341,-45C78.1776,-45 87.1155,-45 96.1116,-45\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"96.254,-48.5001 106.254,-45 96.2539,-41.5001 96.254,-48.5001\"/>\n",
       "</g>\n",
       "<!-- flatten_news -->\n",
       "<g id=\"node3\" class=\"node\">\n",
       "<title>flatten_news</title>\n",
       "<ellipse fill=\"none\" stroke=\"#000000\" cx=\"321.9831\" cy=\"-45\" rx=\"70.3881\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"321.9831\" y=\"-41.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">flatten_news</text>\n",
       "</g>\n",
       "<!-- get_news&#45;&gt;flatten_news -->\n",
       "<g id=\"edge2\" class=\"edge\">\n",
       "<title>get_news&#45;&gt;flatten_news</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M216.0789,-45C224.3179,-45 232.9556,-45 241.5932,-45\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"241.7092,-48.5001 251.7091,-45 241.7091,-41.5001 241.7092,-48.5001\"/>\n",
       "</g>\n",
       "<!-- remote_scale -->\n",
       "<g id=\"node4\" class=\"node\">\n",
       "<title>remote_scale</title>\n",
       "<ellipse fill=\"none\" stroke=\"#000000\" cx=\"500.9704\" cy=\"-45\" rx=\"72.5877\" ry=\"18\"/>\n",
       "<text text-anchor=\"middle\" x=\"500.9704\" y=\"-41.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">remote_scale</text>\n",
       "</g>\n",
       "<!-- flatten_news&#45;&gt;remote_scale -->\n",
       "<g id=\"edge3\" class=\"edge\">\n",
       "<title>flatten_news&#45;&gt;remote_scale</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M392.2099,-45C400.6571,-45 409.3447,-45 417.952,-45\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"418.0001,-48.5001 428.0001,-45 418,-41.5001 418.0001,-48.5001\"/>\n",
       "</g>\n",
       "<!-- parquet -->\n",
       "<g id=\"node5\" class=\"node\">\n",
       "<title>parquet</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M682.764,-86.7273C682.764,-88.5331 666.4041,-90 646.264,-90 626.1239,-90 609.764,-88.5331 609.764,-86.7273 609.764,-86.7273 609.764,-57.2727 609.764,-57.2727 609.764,-55.4669 626.1239,-54 646.264,-54 666.4041,-54 682.764,-55.4669 682.764,-57.2727 682.764,-57.2727 682.764,-86.7273 682.764,-86.7273\"/>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M682.764,-86.7273C682.764,-84.9214 666.4041,-83.4545 646.264,-83.4545 626.1239,-83.4545 609.764,-84.9214 609.764,-86.7273\"/>\n",
       "<text text-anchor=\"middle\" x=\"646.264\" y=\"-68.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">parquet</text>\n",
       "</g>\n",
       "<!-- remote_scale&#45;&gt;parquet -->\n",
       "<g id=\"edge4\" class=\"edge\">\n",
       "<title>remote_scale&#45;&gt;parquet</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M559.2297,-55.8264C572.6855,-58.3269 586.8274,-60.9549 599.7074,-63.3484\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"599.2581,-66.8247 609.7293,-65.2107 600.5371,-59.9425 599.2581,-66.8247\"/>\n",
       "</g>\n",
       "<!-- nosql -->\n",
       "<g id=\"node6\" class=\"node\">\n",
       "<title>nosql</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M673.764,-32.7273C673.764,-34.5331 661.438,-36 646.264,-36 631.0899,-36 618.764,-34.5331 618.764,-32.7273 618.764,-32.7273 618.764,-3.2727 618.764,-3.2727 618.764,-1.4669 631.0899,0 646.264,0 661.438,0 673.764,-1.4669 673.764,-3.2727 673.764,-3.2727 673.764,-32.7273 673.764,-32.7273\"/>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M673.764,-32.7273C673.764,-30.9214 661.438,-29.4545 646.264,-29.4545 631.0899,-29.4545 618.764,-30.9214 618.764,-32.7273\"/>\n",
       "<text text-anchor=\"middle\" x=\"646.264\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\" fill=\"#000000\">nosql</text>\n",
       "</g>\n",
       "<!-- remote_scale&#45;&gt;nosql -->\n",
       "<g id=\"edge5\" class=\"edge\">\n",
       "<title>remote_scale&#45;&gt;nosql</title>\n",
       "<path fill=\"none\" stroke=\"#000000\" d=\"M559.2297,-34.1736C575.9076,-31.0744 593.6395,-27.7793 608.7163,-24.9775\"/>\n",
       "<polygon fill=\"#000000\" stroke=\"#000000\" points=\"609.4922,-28.3933 618.6844,-23.1251 608.2132,-21.5112 609.4922,-28.3933\"/>\n",
       "</g>\n",
       "</g>\n",
       "</svg>\n"
      ],
      "text/plain": [
       "<graphviz.dot.Digraph at 0x7f9a5f605690>"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import mlrun.feature_store as fstore\n",
    "from mlrun.feature_store.steps import DateExtractor, MapValues\n",
    "import yahoo_fin.stock_info as si\n",
    "\n",
    "# creating feature set\n",
    "news_set = fstore.FeatureSet(\"stocks_news\", \n",
    "                                 entities=[fstore.Entity(\"ticker\")],\n",
    "                                 timestamp_key='Datetime', \n",
    "                                 description=\"stocks news feature set\")\n",
    "\n",
    "# how many tickers data we ingest (make sure same number used for ingesting news)\n",
    "# n_tickers = 4\n",
    "\n",
    "news_set.graph\\\n",
    "    .to(name='get_news',handler='get_news')\\\n",
    "    .to(\"storey.steps.Flatten\", name=\"flatten_news\")\\\n",
    "    .to(RemoteStep(name=\"remote_scale\", url=address, method=\"POST\", max_in_flight=MAX_IN_FLIGHT,timeout=REMOTE_STEP_HTTP_TIMEOUT)) \\\n",
    "#     .to(class_name = mod.SentimentClassifierServing() ,name= \"sentiment_analysis_model\", model_path='https://iguazio-sample-data.s3.amazonaws.com/models/model.pt',\n",
    "#         function='')\\\n",
    "\n",
    "\n",
    "#     .to(\"sentiment_analysis\", \"sentiment_analysis_model\",full_event=True)\\\n",
    "\n",
    "news_set.set_targets(with_defaults=True) \n",
    "news_set.plot(rankdir=\"LR\", with_targets=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Dummy ingestion, Deploying ingestion service and getting ingestion endpoint"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> 2022-05-23 11:03:01,011 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Nvidia Macy’s Zoom Costco Snowflake and Other Stocks to Watch This Week', 'summary': 'Earnings this week will include Zoom Best Buy Toll Brothers Nvidia Snowflake Alibaba Costco Dell and Macy’s Plus FOMC minutes durable goods and income and outlays data', 'link': 'https://finance.yahoo.com/m/cce7b005-6192-3999-8a8b-32dd96c75429/nvidia%2C-macy%E2%80%99s%2C-zoom%2C-costco%2C.html?.tsrc=rss', 'published': 'Mon, 23 May 2022 00:23:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-23 00:23:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Nvidia Macy’s Zoom Costco Snowflake and Other Stocks to Watch This Week', 'summary': 'Earnings this week will include Zoom Best Buy Toll Brothers Nvidia Snowflake Alibaba Costco Dell and Macy’s Plus FOMC minutes durable goods and income and outlays data', 'link': 'https://finance.yahoo.com/m/cce7b005-6192-3999-8a8b-32dd96c75429/nvidia%2C-macy%E2%80%99s%2C-zoom%2C-costco%2C.html?.tsrc=rss', 'published': 'Mon, 23 May 2022 00:23:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-23 00:23:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,015 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Whats in the Cards for Agilent Technologies A Q2 Earnings', 'summary': 'Agilent Technologies A fiscal secondquarter results are expected to reflect portfolio strength and momentum across all segments', 'link': 'https://finance.yahoo.com/news/whats-cards-agilent-technologies-q2-152303594.html?.tsrc=rss', 'published': 'Fri, 20 May 2022 15:23:03 +0000', 'ticker': 'A', 'Datetime': '2022-05-20 15:23:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Whats in the Cards for Agilent Technologies A Q2 Earnings', 'summary': 'Agilent Technologies A fiscal secondquarter results are expected to reflect portfolio strength and momentum across all segments', 'link': 'https://finance.yahoo.com/news/whats-cards-agilent-technologies-q2-152303594.html?.tsrc=rss', 'published': 'Fri, 20 May 2022 15:23:03 +0000', 'ticker': 'A', 'Datetime': '2022-05-20 15:23:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,019 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Announces Cash Dividend of 21 Cents per Share', 'summary': 'SANTA CLARA Calif May 18 2022Agilent Technologies Inc NYSE A today announced a quarterly dividend of 21 cents per share of common stock will be paid on July 27 2022 to all shareholders of record as of the close of business on July 5 2022', 'link': 'https://finance.yahoo.com/news/agilent-announces-cash-dividend-21-200500997.html?.tsrc=rss', 'published': 'Wed, 18 May 2022 20:05:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-18 20:05:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Announces Cash Dividend of 21 Cents per Share', 'summary': 'SANTA CLARA Calif May 18 2022Agilent Technologies Inc NYSE A today announced a quarterly dividend of 21 cents per share of common stock will be paid on July 27 2022 to all shareholders of record as of the close of business on July 5 2022', 'link': 'https://finance.yahoo.com/news/agilent-announces-cash-dividend-21-200500997.html?.tsrc=rss', 'published': 'Wed, 18 May 2022 20:05:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-18 20:05:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,022 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Technologies A Earnings Expected to Grow What to Know Ahead of Next Weeks Release', 'summary': 'Agilent A doesnt possess the right combination of the two key ingredients for a likely earnings beat in its upcoming report Get prepared with the key expectations', 'link': 'https://finance.yahoo.com/news/agilent-technologies-earnings-expected-grow-190007143.html?.tsrc=rss', 'published': 'Tue, 17 May 2022 19:00:07 +0000', 'ticker': 'A', 'Datetime': '2022-05-17 19:00:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Technologies A Earnings Expected to Grow What to Know Ahead of Next Weeks Release', 'summary': 'Agilent A doesnt possess the right combination of the two key ingredients for a likely earnings beat in its upcoming report Get prepared with the key expectations', 'link': 'https://finance.yahoo.com/news/agilent-technologies-earnings-expected-grow-190007143.html?.tsrc=rss', 'published': 'Tue, 17 May 2022 19:00:07 +0000', 'ticker': 'A', 'Datetime': '2022-05-17 19:00:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,026 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark in Europe to Include\\xa0Cervical Cancer', 'summary': 'SANTA CLARA Calif May 10 2022Agilent Technologies Inc NYSE A today announced that its PDL1 IHC 22C3 pharmDx Code SK006 is now EU CEIVD–marked for use in cervical cancer PDL1 IHC 22C3 pharmDx can be used as an aid in identifying cervical cancer patients for whom treatment with KEYTRUDA® pembrolizumab may be appropriate1 KEYTRUDA is an antiPD1 therapy developed by Merck known as MSD outside the US and Canada In Europe KEYTRUDA in combination with chemotherapy with or wi', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-195000276.html?.tsrc=rss', 'published': 'Tue, 10 May 2022 19:50:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-10 19:50:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark in Europe to Include\\xa0Cervical Cancer', 'summary': 'SANTA CLARA Calif May 10 2022Agilent Technologies Inc NYSE A today announced that its PDL1 IHC 22C3 pharmDx Code SK006 is now EU CEIVD–marked for use in cervical cancer PDL1 IHC 22C3 pharmDx can be used as an aid in identifying cervical cancer patients for whom treatment with KEYTRUDA® pembrolizumab may be appropriate1 KEYTRUDA is an antiPD1 therapy developed by Merck known as MSD outside the US and Canada In Europe KEYTRUDA in combination with chemotherapy with or wi', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-195000276.html?.tsrc=rss', 'published': 'Tue, 10 May 2022 19:50:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-10 19:50:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,029 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ken Fisher is Selling These 10 Stocks in 2022', 'summary': 'In this article we will discuss some stocks sold by Ken Fisher in the first quarter You can skip this part and go to read Ken Fisher is Selling These 5 Stocks in 2022 Ken Fisher is one of the most followed finance experts in the world Fisher whose worth stands at 5 billion is …', 'link': 'https://finance.yahoo.com/news/ken-fisher-selling-10-stocks-205550096.html?.tsrc=rss', 'published': 'Fri, 06 May 2022 20:55:50 +0000', 'ticker': 'A', 'Datetime': '2022-05-06 20:55:50'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ken Fisher is Selling These 10 Stocks in 2022', 'summary': 'In this article we will discuss some stocks sold by Ken Fisher in the first quarter You can skip this part and go to read Ken Fisher is Selling These 5 Stocks in 2022 Ken Fisher is one of the most followed finance experts in the world Fisher whose worth stands at 5 billion is …', 'link': 'https://finance.yahoo.com/news/ken-fisher-selling-10-stocks-205550096.html?.tsrc=rss', 'published': 'Fri, 06 May 2022 20:55:50 +0000', 'ticker': 'A', 'Datetime': '2022-05-06 20:55:50'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,033 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Cognex Corporation CGNX Q1 Earnings and Revenues Top Estimates', 'summary': 'Cognex Corporation CGNX delivered earnings and revenue surprises of 769 and 233 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/cognex-corporation-cgnx-q1-earnings-220510875.html?.tsrc=rss', 'published': 'Thu, 05 May 2022 22:05:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-05 22:05:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Cognex Corporation CGNX Q1 Earnings and Revenues Top Estimates', 'summary': 'Cognex Corporation CGNX delivered earnings and revenue surprises of 769 and 233 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/cognex-corporation-cgnx-q1-earnings-220510875.html?.tsrc=rss', 'published': 'Thu, 05 May 2022 22:05:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-05 22:05:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,036 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Wolfspeed WOLF Reports Q3 Loss Misses Revenue Estimates', 'summary': 'Wolfspeed WOLF delivered earnings and revenue surprises of 1429 and 128 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/wolfspeed-wolf-reports-q3-loss-225510454.html?.tsrc=rss', 'published': 'Wed, 04 May 2022 22:55:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-04 22:55:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Wolfspeed WOLF Reports Q3 Loss Misses Revenue Estimates', 'summary': 'Wolfspeed WOLF delivered earnings and revenue surprises of 1429 and 128 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/wolfspeed-wolf-reports-q3-loss-225510454.html?.tsrc=rss', 'published': 'Wed, 04 May 2022 22:55:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-04 22:55:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,039 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ametek AME Tops Q1 Earnings Estimates', 'summary': 'Ametek AME delivered earnings and revenue surprises of 472 and 017 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/ametek-ame-tops-q1-earnings-121512940.html?.tsrc=rss', 'published': 'Tue, 03 May 2022 12:15:12 +0000', 'ticker': 'A', 'Datetime': '2022-05-03 12:15:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ametek AME Tops Q1 Earnings Estimates', 'summary': 'Ametek AME delivered earnings and revenue surprises of 472 and 017 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/ametek-ame-tops-q1-earnings-121512940.html?.tsrc=rss', 'published': 'Tue, 03 May 2022 12:15:12 +0000', 'ticker': 'A', 'Datetime': '2022-05-03 12:15:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,043 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'National Instruments NATI Misses Q1 Earnings and Revenue Estimates', 'summary': 'National Instruments NATI delivered earnings and revenue surprises of 682 and 469 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/national-instruments-nati-misses-q1-213509121.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 21:35:09 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 21:35:09'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'National Instruments NATI Misses Q1 Earnings and Revenue Estimates', 'summary': 'National Instruments NATI delivered earnings and revenue surprises of 682 and 469 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/national-instruments-nati-misses-q1-213509121.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 21:35:09 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 21:35:09'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,046 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Is Weakness In Agilent Technologies Inc NYSEA Stock A Sign That The Market Could be Wrong Given Its Strong Financial Prospects', 'summary': 'It is hard to get excited after looking at Agilent Technologies NYSEA recent performance when its stock has', 'link': 'https://finance.yahoo.com/news/weakness-agilent-technologies-inc-nyse-101304525.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 10:13:04 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 10:13:04'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Is Weakness In Agilent Technologies Inc NYSEA Stock A Sign That The Market Could be Wrong Given Its Strong Financial Prospects', 'summary': 'It is hard to get excited after looking at Agilent Technologies NYSEA recent performance when its stock has', 'link': 'https://finance.yahoo.com/news/weakness-agilent-technologies-inc-nyse-101304525.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 10:13:04 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 10:13:04'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,050 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent to Announce SecondQuarter Fiscal Year 2022 Financial Results May 24', 'summary': 'SANTA CLARA Calif April 26 2022Agilent Technologies Inc NYSE A today announced that it will release financial results for the second quarter of fiscal year 2022 after the stock market closes on Tuesday May 24 The company will host a live webcast of its investor conference call in listenonly mode on the same day', 'link': 'https://finance.yahoo.com/news/agilent-announce-second-quarter-fiscal-150000331.html?.tsrc=rss', 'published': 'Tue, 26 Apr 2022 15:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-26 15:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent to Announce SecondQuarter Fiscal Year 2022 Financial Results May 24', 'summary': 'SANTA CLARA Calif April 26 2022Agilent Technologies Inc NYSE A today announced that it will release financial results for the second quarter of fiscal year 2022 after the stock market closes on Tuesday May 24 The company will host a live webcast of its investor conference call in listenonly mode on the same day', 'link': 'https://finance.yahoo.com/news/agilent-announce-second-quarter-fiscal-150000331.html?.tsrc=rss', 'published': 'Tue, 26 Apr 2022 15:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-26 15:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,053 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Joins the National Institute for Innovation in Manufacturing to Advance Biomanufacturing', 'summary': 'SANTA CLARA Calif April 19 2022Agilent Technologies Inc NYSE A announced that it has joined the National Institute for Innovation in Manufacturing to Advance Biomanufacturing NIIMBL Membership in NIIMBL demonstrates Agilent’s commitment to supporting biopharma and biotherapeutics customer challenges through partnership and innovation using tools and workflows', 'link': 'https://finance.yahoo.com/news/agilent-joins-national-institute-innovation-120000496.html?.tsrc=rss', 'published': 'Tue, 19 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-19 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Joins the National Institute for Innovation in Manufacturing to Advance Biomanufacturing', 'summary': 'SANTA CLARA Calif April 19 2022Agilent Technologies Inc NYSE A announced that it has joined the National Institute for Innovation in Manufacturing to Advance Biomanufacturing NIIMBL Membership in NIIMBL demonstrates Agilent’s commitment to supporting biopharma and biotherapeutics customer challenges through partnership and innovation using tools and workflows', 'link': 'https://finance.yahoo.com/news/agilent-joins-national-institute-innovation-120000496.html?.tsrc=rss', 'published': 'Tue, 19 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-19 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,057 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Zacks Industry Outlook Highlights Agilent Technologies AMETEK Fortive and Cognex', 'summary': 'Agilent Technologies AMETEK Fortive and Cognex Zacks Industry Outlook article', 'link': 'https://finance.yahoo.com/news/zacks-industry-outlook-highlights-agilent-120812836.html?.tsrc=rss', 'published': 'Wed, 13 Apr 2022 12:08:12 +0000', 'ticker': 'A', 'Datetime': '2022-04-13 12:08:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Zacks Industry Outlook Highlights Agilent Technologies AMETEK Fortive and Cognex', 'summary': 'Agilent Technologies AMETEK Fortive and Cognex Zacks Industry Outlook article', 'link': 'https://finance.yahoo.com/news/zacks-industry-outlook-highlights-agilent-120812836.html?.tsrc=rss', 'published': 'Wed, 13 Apr 2022 12:08:12 +0000', 'ticker': 'A', 'Datetime': '2022-04-13 12:08:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,060 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': '4 Testing Equipment Stocks to Escape a Challenging Industry', 'summary': 'Coronavirusled disruptions are hurting the Zacks Electronics  Testing Equipment industry However industry participants like A AME FTV and CGNX are set to gain from 5G prospects', 'link': 'https://finance.yahoo.com/news/4-testing-equipment-stocks-escape-191407848.html?.tsrc=rss', 'published': 'Tue, 12 Apr 2022 19:14:07 +0000', 'ticker': 'A', 'Datetime': '2022-04-12 19:14:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': '4 Testing Equipment Stocks to Escape a Challenging Industry', 'summary': 'Coronavirusled disruptions are hurting the Zacks Electronics  Testing Equipment industry However industry participants like A AME FTV and CGNX are set to gain from 5G prospects', 'link': 'https://finance.yahoo.com/news/4-testing-equipment-stocks-escape-191407848.html?.tsrc=rss', 'published': 'Tue, 12 Apr 2022 19:14:07 +0000', 'ticker': 'A', 'Datetime': '2022-04-12 19:14:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,064 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Highlights Genomics and Cell Analysis Solutions for Cancer Research at AACR 2022', 'summary': 'SANTA CLARA Calif April 08 2022Agilent Technologies Inc NYSE A today announced cancer research innovations in cell analysis and genomics that will be on show at the American Association for Cancer Research Annual Meeting being held April 8  13 2022 in New Orleans Louisiana', 'link': 'https://finance.yahoo.com/news/agilent-highlights-genomics-cell-analysis-120000541.html?.tsrc=rss', 'published': 'Fri, 08 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-08 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Highlights Genomics and Cell Analysis Solutions for Cancer Research at AACR 2022', 'summary': 'SANTA CLARA Calif April 08 2022Agilent Technologies Inc NYSE A today announced cancer research innovations in cell analysis and genomics that will be on show at the American Association for Cancer Research Annual Meeting being held April 8  13 2022 in New Orleans Louisiana', 'link': 'https://finance.yahoo.com/news/agilent-highlights-genomics-cell-analysis-120000541.html?.tsrc=rss', 'published': 'Fri, 08 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-08 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,067 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent A Boosts PDL1 IHC 288 pharmDX Use in European Union', 'summary': 'Agilent Technologies A boosts its presence in the companion diagnostics market by expanding the use of PDL1 IHC 288 pharmDx assay for esophageal squamous cell carcinoma treatment in the EU', 'link': 'https://finance.yahoo.com/news/agilent-boosts-pd-l1-ihc-151903069.html?.tsrc=rss', 'published': 'Thu, 07 Apr 2022 15:19:03 +0000', 'ticker': 'A', 'Datetime': '2022-04-07 15:19:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent A Boosts PDL1 IHC 288 pharmDX Use in European Union', 'summary': 'Agilent Technologies A boosts its presence in the companion diagnostics market by expanding the use of PDL1 IHC 288 pharmDx assay for esophageal squamous cell carcinoma treatment in the EU', 'link': 'https://finance.yahoo.com/news/agilent-boosts-pd-l1-ihc-151903069.html?.tsrc=rss', 'published': 'Thu, 07 Apr 2022 15:19:03 +0000', 'ticker': 'A', 'Datetime': '2022-04-07 15:19:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,070 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include MuscleInvasive Urothelial Carcinoma MIUC', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx immunohistochemical assay to extend the use of the test to patients diagnosed with muscleinvasive urothelial carcinoma MIUC who have tumor cell PDL1 expression ≥ 1 for adjuvant treatment with OPDIVO® nivolumab a PD1targeted immunotherapeutic from Bristol Myers Squibb', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-122500695.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:25:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:25:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include MuscleInvasive Urothelial Carcinoma MIUC', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx immunohistochemical assay to extend the use of the test to patients diagnosed with muscleinvasive urothelial carcinoma MIUC who have tumor cell PDL1 expression ≥ 1 for adjuvant treatment with OPDIVO® nivolumab a PD1targeted immunotherapeutic from Bristol Myers Squibb', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-122500695.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:25:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:25:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,074 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include Esophageal Squamous Cell Carcinoma', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced it has expanded CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx as an aid in identifying esophageal squamous cell carcinoma patients for treatment with Bristol Myers Squibb’s PD1targeted immunotherapeutic OPDIVO® nivolumab in combination with fluoropyrimidine and platinumbased chemotherapy or OPDIVO® in combination with YERVOY® ipilimumab These combined treatments provide new hop', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-121500724.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:15:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:15:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include Esophageal Squamous Cell Carcinoma', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced it has expanded CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx as an aid in identifying esophageal squamous cell carcinoma patients for treatment with Bristol Myers Squibb’s PD1targeted immunotherapeutic OPDIVO® nivolumab in combination with fluoropyrimidine and platinumbased chemotherapy or OPDIVO® in combination with YERVOY® ipilimumab These combined treatments provide new hop', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-121500724.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:15:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:15:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:01,077 [error] Pushing error to error stream: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Why Savvy Investors Look For Ports In Storms Like Agilent Thermo Fisher And Others', 'summary': 'As supply chain constraints continue to squeeze health care stocks one analyst suggested Monday to look for ports in storms', 'link': 'https://finance.yahoo.com/m/ed970478-a7f1-390a-8d29-013d389edc51/why-savvy-investors-look-for.html?.tsrc=rss', 'published': 'Mon, 04 Apr 2022 20:10:02 +0000', 'ticker': 'A', 'Datetime': '2022-04-04 20:10:02'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=0b99c55be1d044b3b392aef693ec5585-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Why Savvy Investors Look For Ports In Storms Like Agilent Thermo Fisher And Others', 'summary': 'As supply chain constraints continue to squeeze health care stocks one analyst suggested Monday to look for ports in storms', 'link': 'https://finance.yahoo.com/m/ed970478-a7f1-390a-8d29-013d389edc51/why-savvy-investors-look-for.html?.tsrc=rss', 'published': 'Mon, 04 Apr 2022 20:10:02 +0000', 'ticker': 'A', 'Datetime': '2022-04-04 20:10:02'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Unclosed client session\n",
      "client_session: <aiohttp.client.ClientSession object at 0x7f9a60dabb50>\n",
      "Unclosed connector\n",
      "connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f99b362a2f0>, 351580.941085256)]']\n",
      "connector: <aiohttp.connector.TCPConnector object at 0x7f99c0e2c590>\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> 2022-05-23 11:03:02,673 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Nvidia Macy’s Zoom Costco Snowflake and Other Stocks to Watch This Week', 'summary': 'Earnings this week will include Zoom Best Buy Toll Brothers Nvidia Snowflake Alibaba Costco Dell and Macy’s Plus FOMC minutes durable goods and income and outlays data', 'link': 'https://finance.yahoo.com/m/cce7b005-6192-3999-8a8b-32dd96c75429/nvidia%2C-macy%E2%80%99s%2C-zoom%2C-costco%2C.html?.tsrc=rss', 'published': 'Mon, 23 May 2022 00:23:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-23 00:23:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Nvidia Macy’s Zoom Costco Snowflake and Other Stocks to Watch This Week', 'summary': 'Earnings this week will include Zoom Best Buy Toll Brothers Nvidia Snowflake Alibaba Costco Dell and Macy’s Plus FOMC minutes durable goods and income and outlays data', 'link': 'https://finance.yahoo.com/m/cce7b005-6192-3999-8a8b-32dd96c75429/nvidia%2C-macy%E2%80%99s%2C-zoom%2C-costco%2C.html?.tsrc=rss', 'published': 'Mon, 23 May 2022 00:23:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-23 00:23:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,673 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Nvidia Macy’s Zoom Costco Snowflake and Other Stocks to Watch This Week', 'summary': 'Earnings this week will include Zoom Best Buy Toll Brothers Nvidia Snowflake Alibaba Costco Dell and Macy’s Plus FOMC minutes durable goods and income and outlays data', 'link': 'https://finance.yahoo.com/m/cce7b005-6192-3999-8a8b-32dd96c75429/nvidia%2C-macy%E2%80%99s%2C-zoom%2C-costco%2C.html?.tsrc=rss', 'published': 'Mon, 23 May 2022 00:23:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-23 00:23:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Nvidia Macy’s Zoom Costco Snowflake and Other Stocks to Watch This Week', 'summary': 'Earnings this week will include Zoom Best Buy Toll Brothers Nvidia Snowflake Alibaba Costco Dell and Macy’s Plus FOMC minutes durable goods and income and outlays data', 'link': 'https://finance.yahoo.com/m/cce7b005-6192-3999-8a8b-32dd96c75429/nvidia%2C-macy%E2%80%99s%2C-zoom%2C-costco%2C.html?.tsrc=rss', 'published': 'Mon, 23 May 2022 00:23:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-23 00:23:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,677 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Whats in the Cards for Agilent Technologies A Q2 Earnings', 'summary': 'Agilent Technologies A fiscal secondquarter results are expected to reflect portfolio strength and momentum across all segments', 'link': 'https://finance.yahoo.com/news/whats-cards-agilent-technologies-q2-152303594.html?.tsrc=rss', 'published': 'Fri, 20 May 2022 15:23:03 +0000', 'ticker': 'A', 'Datetime': '2022-05-20 15:23:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Whats in the Cards for Agilent Technologies A Q2 Earnings', 'summary': 'Agilent Technologies A fiscal secondquarter results are expected to reflect portfolio strength and momentum across all segments', 'link': 'https://finance.yahoo.com/news/whats-cards-agilent-technologies-q2-152303594.html?.tsrc=rss', 'published': 'Fri, 20 May 2022 15:23:03 +0000', 'ticker': 'A', 'Datetime': '2022-05-20 15:23:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,677 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Whats in the Cards for Agilent Technologies A Q2 Earnings', 'summary': 'Agilent Technologies A fiscal secondquarter results are expected to reflect portfolio strength and momentum across all segments', 'link': 'https://finance.yahoo.com/news/whats-cards-agilent-technologies-q2-152303594.html?.tsrc=rss', 'published': 'Fri, 20 May 2022 15:23:03 +0000', 'ticker': 'A', 'Datetime': '2022-05-20 15:23:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Whats in the Cards for Agilent Technologies A Q2 Earnings', 'summary': 'Agilent Technologies A fiscal secondquarter results are expected to reflect portfolio strength and momentum across all segments', 'link': 'https://finance.yahoo.com/news/whats-cards-agilent-technologies-q2-152303594.html?.tsrc=rss', 'published': 'Fri, 20 May 2022 15:23:03 +0000', 'ticker': 'A', 'Datetime': '2022-05-20 15:23:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,681 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Announces Cash Dividend of 21 Cents per Share', 'summary': 'SANTA CLARA Calif May 18 2022Agilent Technologies Inc NYSE A today announced a quarterly dividend of 21 cents per share of common stock will be paid on July 27 2022 to all shareholders of record as of the close of business on July 5 2022', 'link': 'https://finance.yahoo.com/news/agilent-announces-cash-dividend-21-200500997.html?.tsrc=rss', 'published': 'Wed, 18 May 2022 20:05:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-18 20:05:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Announces Cash Dividend of 21 Cents per Share', 'summary': 'SANTA CLARA Calif May 18 2022Agilent Technologies Inc NYSE A today announced a quarterly dividend of 21 cents per share of common stock will be paid on July 27 2022 to all shareholders of record as of the close of business on July 5 2022', 'link': 'https://finance.yahoo.com/news/agilent-announces-cash-dividend-21-200500997.html?.tsrc=rss', 'published': 'Wed, 18 May 2022 20:05:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-18 20:05:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,681 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Announces Cash Dividend of 21 Cents per Share', 'summary': 'SANTA CLARA Calif May 18 2022Agilent Technologies Inc NYSE A today announced a quarterly dividend of 21 cents per share of common stock will be paid on July 27 2022 to all shareholders of record as of the close of business on July 5 2022', 'link': 'https://finance.yahoo.com/news/agilent-announces-cash-dividend-21-200500997.html?.tsrc=rss', 'published': 'Wed, 18 May 2022 20:05:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-18 20:05:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Announces Cash Dividend of 21 Cents per Share', 'summary': 'SANTA CLARA Calif May 18 2022Agilent Technologies Inc NYSE A today announced a quarterly dividend of 21 cents per share of common stock will be paid on July 27 2022 to all shareholders of record as of the close of business on July 5 2022', 'link': 'https://finance.yahoo.com/news/agilent-announces-cash-dividend-21-200500997.html?.tsrc=rss', 'published': 'Wed, 18 May 2022 20:05:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-18 20:05:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,685 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Technologies A Earnings Expected to Grow What to Know Ahead of Next Weeks Release', 'summary': 'Agilent A doesnt possess the right combination of the two key ingredients for a likely earnings beat in its upcoming report Get prepared with the key expectations', 'link': 'https://finance.yahoo.com/news/agilent-technologies-earnings-expected-grow-190007143.html?.tsrc=rss', 'published': 'Tue, 17 May 2022 19:00:07 +0000', 'ticker': 'A', 'Datetime': '2022-05-17 19:00:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Technologies A Earnings Expected to Grow What to Know Ahead of Next Weeks Release', 'summary': 'Agilent A doesnt possess the right combination of the two key ingredients for a likely earnings beat in its upcoming report Get prepared with the key expectations', 'link': 'https://finance.yahoo.com/news/agilent-technologies-earnings-expected-grow-190007143.html?.tsrc=rss', 'published': 'Tue, 17 May 2022 19:00:07 +0000', 'ticker': 'A', 'Datetime': '2022-05-17 19:00:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,685 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Technologies A Earnings Expected to Grow What to Know Ahead of Next Weeks Release', 'summary': 'Agilent A doesnt possess the right combination of the two key ingredients for a likely earnings beat in its upcoming report Get prepared with the key expectations', 'link': 'https://finance.yahoo.com/news/agilent-technologies-earnings-expected-grow-190007143.html?.tsrc=rss', 'published': 'Tue, 17 May 2022 19:00:07 +0000', 'ticker': 'A', 'Datetime': '2022-05-17 19:00:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Technologies A Earnings Expected to Grow What to Know Ahead of Next Weeks Release', 'summary': 'Agilent A doesnt possess the right combination of the two key ingredients for a likely earnings beat in its upcoming report Get prepared with the key expectations', 'link': 'https://finance.yahoo.com/news/agilent-technologies-earnings-expected-grow-190007143.html?.tsrc=rss', 'published': 'Tue, 17 May 2022 19:00:07 +0000', 'ticker': 'A', 'Datetime': '2022-05-17 19:00:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,692 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark in Europe to Include\\xa0Cervical Cancer', 'summary': 'SANTA CLARA Calif May 10 2022Agilent Technologies Inc NYSE A today announced that its PDL1 IHC 22C3 pharmDx Code SK006 is now EU CEIVD–marked for use in cervical cancer PDL1 IHC 22C3 pharmDx can be used as an aid in identifying cervical cancer patients for whom treatment with KEYTRUDA® pembrolizumab may be appropriate1 KEYTRUDA is an antiPD1 therapy developed by Merck known as MSD outside the US and Canada In Europe KEYTRUDA in combination with chemotherapy with or wi', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-195000276.html?.tsrc=rss', 'published': 'Tue, 10 May 2022 19:50:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-10 19:50:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark in Europe to Include\\xa0Cervical Cancer', 'summary': 'SANTA CLARA Calif May 10 2022Agilent Technologies Inc NYSE A today announced that its PDL1 IHC 22C3 pharmDx Code SK006 is now EU CEIVD–marked for use in cervical cancer PDL1 IHC 22C3 pharmDx can be used as an aid in identifying cervical cancer patients for whom treatment with KEYTRUDA® pembrolizumab may be appropriate1 KEYTRUDA is an antiPD1 therapy developed by Merck known as MSD outside the US and Canada In Europe KEYTRUDA in combination with chemotherapy with or wi', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-195000276.html?.tsrc=rss', 'published': 'Tue, 10 May 2022 19:50:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-10 19:50:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,692 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark in Europe to Include\\xa0Cervical Cancer', 'summary': 'SANTA CLARA Calif May 10 2022Agilent Technologies Inc NYSE A today announced that its PDL1 IHC 22C3 pharmDx Code SK006 is now EU CEIVD–marked for use in cervical cancer PDL1 IHC 22C3 pharmDx can be used as an aid in identifying cervical cancer patients for whom treatment with KEYTRUDA® pembrolizumab may be appropriate1 KEYTRUDA is an antiPD1 therapy developed by Merck known as MSD outside the US and Canada In Europe KEYTRUDA in combination with chemotherapy with or wi', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-195000276.html?.tsrc=rss', 'published': 'Tue, 10 May 2022 19:50:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-10 19:50:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark in Europe to Include\\xa0Cervical Cancer', 'summary': 'SANTA CLARA Calif May 10 2022Agilent Technologies Inc NYSE A today announced that its PDL1 IHC 22C3 pharmDx Code SK006 is now EU CEIVD–marked for use in cervical cancer PDL1 IHC 22C3 pharmDx can be used as an aid in identifying cervical cancer patients for whom treatment with KEYTRUDA® pembrolizumab may be appropriate1 KEYTRUDA is an antiPD1 therapy developed by Merck known as MSD outside the US and Canada In Europe KEYTRUDA in combination with chemotherapy with or wi', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-195000276.html?.tsrc=rss', 'published': 'Tue, 10 May 2022 19:50:00 +0000', 'ticker': 'A', 'Datetime': '2022-05-10 19:50:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,696 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ken Fisher is Selling These 10 Stocks in 2022', 'summary': 'In this article we will discuss some stocks sold by Ken Fisher in the first quarter You can skip this part and go to read Ken Fisher is Selling These 5 Stocks in 2022 Ken Fisher is one of the most followed finance experts in the world Fisher whose worth stands at 5 billion is …', 'link': 'https://finance.yahoo.com/news/ken-fisher-selling-10-stocks-205550096.html?.tsrc=rss', 'published': 'Fri, 06 May 2022 20:55:50 +0000', 'ticker': 'A', 'Datetime': '2022-05-06 20:55:50'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ken Fisher is Selling These 10 Stocks in 2022', 'summary': 'In this article we will discuss some stocks sold by Ken Fisher in the first quarter You can skip this part and go to read Ken Fisher is Selling These 5 Stocks in 2022 Ken Fisher is one of the most followed finance experts in the world Fisher whose worth stands at 5 billion is …', 'link': 'https://finance.yahoo.com/news/ken-fisher-selling-10-stocks-205550096.html?.tsrc=rss', 'published': 'Fri, 06 May 2022 20:55:50 +0000', 'ticker': 'A', 'Datetime': '2022-05-06 20:55:50'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,696 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ken Fisher is Selling These 10 Stocks in 2022', 'summary': 'In this article we will discuss some stocks sold by Ken Fisher in the first quarter You can skip this part and go to read Ken Fisher is Selling These 5 Stocks in 2022 Ken Fisher is one of the most followed finance experts in the world Fisher whose worth stands at 5 billion is …', 'link': 'https://finance.yahoo.com/news/ken-fisher-selling-10-stocks-205550096.html?.tsrc=rss', 'published': 'Fri, 06 May 2022 20:55:50 +0000', 'ticker': 'A', 'Datetime': '2022-05-06 20:55:50'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ken Fisher is Selling These 10 Stocks in 2022', 'summary': 'In this article we will discuss some stocks sold by Ken Fisher in the first quarter You can skip this part and go to read Ken Fisher is Selling These 5 Stocks in 2022 Ken Fisher is one of the most followed finance experts in the world Fisher whose worth stands at 5 billion is …', 'link': 'https://finance.yahoo.com/news/ken-fisher-selling-10-stocks-205550096.html?.tsrc=rss', 'published': 'Fri, 06 May 2022 20:55:50 +0000', 'ticker': 'A', 'Datetime': '2022-05-06 20:55:50'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,700 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Cognex Corporation CGNX Q1 Earnings and Revenues Top Estimates', 'summary': 'Cognex Corporation CGNX delivered earnings and revenue surprises of 769 and 233 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/cognex-corporation-cgnx-q1-earnings-220510875.html?.tsrc=rss', 'published': 'Thu, 05 May 2022 22:05:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-05 22:05:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Cognex Corporation CGNX Q1 Earnings and Revenues Top Estimates', 'summary': 'Cognex Corporation CGNX delivered earnings and revenue surprises of 769 and 233 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/cognex-corporation-cgnx-q1-earnings-220510875.html?.tsrc=rss', 'published': 'Thu, 05 May 2022 22:05:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-05 22:05:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,700 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Cognex Corporation CGNX Q1 Earnings and Revenues Top Estimates', 'summary': 'Cognex Corporation CGNX delivered earnings and revenue surprises of 769 and 233 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/cognex-corporation-cgnx-q1-earnings-220510875.html?.tsrc=rss', 'published': 'Thu, 05 May 2022 22:05:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-05 22:05:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Cognex Corporation CGNX Q1 Earnings and Revenues Top Estimates', 'summary': 'Cognex Corporation CGNX delivered earnings and revenue surprises of 769 and 233 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/cognex-corporation-cgnx-q1-earnings-220510875.html?.tsrc=rss', 'published': 'Thu, 05 May 2022 22:05:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-05 22:05:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,704 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Wolfspeed WOLF Reports Q3 Loss Misses Revenue Estimates', 'summary': 'Wolfspeed WOLF delivered earnings and revenue surprises of 1429 and 128 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/wolfspeed-wolf-reports-q3-loss-225510454.html?.tsrc=rss', 'published': 'Wed, 04 May 2022 22:55:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-04 22:55:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Wolfspeed WOLF Reports Q3 Loss Misses Revenue Estimates', 'summary': 'Wolfspeed WOLF delivered earnings and revenue surprises of 1429 and 128 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/wolfspeed-wolf-reports-q3-loss-225510454.html?.tsrc=rss', 'published': 'Wed, 04 May 2022 22:55:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-04 22:55:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,704 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Wolfspeed WOLF Reports Q3 Loss Misses Revenue Estimates', 'summary': 'Wolfspeed WOLF delivered earnings and revenue surprises of 1429 and 128 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/wolfspeed-wolf-reports-q3-loss-225510454.html?.tsrc=rss', 'published': 'Wed, 04 May 2022 22:55:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-04 22:55:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Wolfspeed WOLF Reports Q3 Loss Misses Revenue Estimates', 'summary': 'Wolfspeed WOLF delivered earnings and revenue surprises of 1429 and 128 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/wolfspeed-wolf-reports-q3-loss-225510454.html?.tsrc=rss', 'published': 'Wed, 04 May 2022 22:55:10 +0000', 'ticker': 'A', 'Datetime': '2022-05-04 22:55:10'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,708 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ametek AME Tops Q1 Earnings Estimates', 'summary': 'Ametek AME delivered earnings and revenue surprises of 472 and 017 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/ametek-ame-tops-q1-earnings-121512940.html?.tsrc=rss', 'published': 'Tue, 03 May 2022 12:15:12 +0000', 'ticker': 'A', 'Datetime': '2022-05-03 12:15:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ametek AME Tops Q1 Earnings Estimates', 'summary': 'Ametek AME delivered earnings and revenue surprises of 472 and 017 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/ametek-ame-tops-q1-earnings-121512940.html?.tsrc=rss', 'published': 'Tue, 03 May 2022 12:15:12 +0000', 'ticker': 'A', 'Datetime': '2022-05-03 12:15:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,708 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ametek AME Tops Q1 Earnings Estimates', 'summary': 'Ametek AME delivered earnings and revenue surprises of 472 and 017 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/ametek-ame-tops-q1-earnings-121512940.html?.tsrc=rss', 'published': 'Tue, 03 May 2022 12:15:12 +0000', 'ticker': 'A', 'Datetime': '2022-05-03 12:15:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Ametek AME Tops Q1 Earnings Estimates', 'summary': 'Ametek AME delivered earnings and revenue surprises of 472 and 017 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/ametek-ame-tops-q1-earnings-121512940.html?.tsrc=rss', 'published': 'Tue, 03 May 2022 12:15:12 +0000', 'ticker': 'A', 'Datetime': '2022-05-03 12:15:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,712 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'National Instruments NATI Misses Q1 Earnings and Revenue Estimates', 'summary': 'National Instruments NATI delivered earnings and revenue surprises of 682 and 469 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/national-instruments-nati-misses-q1-213509121.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 21:35:09 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 21:35:09'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'National Instruments NATI Misses Q1 Earnings and Revenue Estimates', 'summary': 'National Instruments NATI delivered earnings and revenue surprises of 682 and 469 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/national-instruments-nati-misses-q1-213509121.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 21:35:09 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 21:35:09'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,712 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'National Instruments NATI Misses Q1 Earnings and Revenue Estimates', 'summary': 'National Instruments NATI delivered earnings and revenue surprises of 682 and 469 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/national-instruments-nati-misses-q1-213509121.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 21:35:09 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 21:35:09'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'National Instruments NATI Misses Q1 Earnings and Revenue Estimates', 'summary': 'National Instruments NATI delivered earnings and revenue surprises of 682 and 469 respectively for the quarter ended March 2022 Do the numbers hold clues to what lies ahead for the stock', 'link': 'https://finance.yahoo.com/news/national-instruments-nati-misses-q1-213509121.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 21:35:09 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 21:35:09'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,716 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Is Weakness In Agilent Technologies Inc NYSEA Stock A Sign That The Market Could be Wrong Given Its Strong Financial Prospects', 'summary': 'It is hard to get excited after looking at Agilent Technologies NYSEA recent performance when its stock has', 'link': 'https://finance.yahoo.com/news/weakness-agilent-technologies-inc-nyse-101304525.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 10:13:04 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 10:13:04'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Is Weakness In Agilent Technologies Inc NYSEA Stock A Sign That The Market Could be Wrong Given Its Strong Financial Prospects', 'summary': 'It is hard to get excited after looking at Agilent Technologies NYSEA recent performance when its stock has', 'link': 'https://finance.yahoo.com/news/weakness-agilent-technologies-inc-nyse-101304525.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 10:13:04 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 10:13:04'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,716 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Is Weakness In Agilent Technologies Inc NYSEA Stock A Sign That The Market Could be Wrong Given Its Strong Financial Prospects', 'summary': 'It is hard to get excited after looking at Agilent Technologies NYSEA recent performance when its stock has', 'link': 'https://finance.yahoo.com/news/weakness-agilent-technologies-inc-nyse-101304525.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 10:13:04 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 10:13:04'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Is Weakness In Agilent Technologies Inc NYSEA Stock A Sign That The Market Could be Wrong Given Its Strong Financial Prospects', 'summary': 'It is hard to get excited after looking at Agilent Technologies NYSEA recent performance when its stock has', 'link': 'https://finance.yahoo.com/news/weakness-agilent-technologies-inc-nyse-101304525.html?.tsrc=rss', 'published': 'Thu, 28 Apr 2022 10:13:04 +0000', 'ticker': 'A', 'Datetime': '2022-04-28 10:13:04'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,720 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent to Announce SecondQuarter Fiscal Year 2022 Financial Results May 24', 'summary': 'SANTA CLARA Calif April 26 2022Agilent Technologies Inc NYSE A today announced that it will release financial results for the second quarter of fiscal year 2022 after the stock market closes on Tuesday May 24 The company will host a live webcast of its investor conference call in listenonly mode on the same day', 'link': 'https://finance.yahoo.com/news/agilent-announce-second-quarter-fiscal-150000331.html?.tsrc=rss', 'published': 'Tue, 26 Apr 2022 15:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-26 15:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent to Announce SecondQuarter Fiscal Year 2022 Financial Results May 24', 'summary': 'SANTA CLARA Calif April 26 2022Agilent Technologies Inc NYSE A today announced that it will release financial results for the second quarter of fiscal year 2022 after the stock market closes on Tuesday May 24 The company will host a live webcast of its investor conference call in listenonly mode on the same day', 'link': 'https://finance.yahoo.com/news/agilent-announce-second-quarter-fiscal-150000331.html?.tsrc=rss', 'published': 'Tue, 26 Apr 2022 15:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-26 15:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,720 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent to Announce SecondQuarter Fiscal Year 2022 Financial Results May 24', 'summary': 'SANTA CLARA Calif April 26 2022Agilent Technologies Inc NYSE A today announced that it will release financial results for the second quarter of fiscal year 2022 after the stock market closes on Tuesday May 24 The company will host a live webcast of its investor conference call in listenonly mode on the same day', 'link': 'https://finance.yahoo.com/news/agilent-announce-second-quarter-fiscal-150000331.html?.tsrc=rss', 'published': 'Tue, 26 Apr 2022 15:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-26 15:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent to Announce SecondQuarter Fiscal Year 2022 Financial Results May 24', 'summary': 'SANTA CLARA Calif April 26 2022Agilent Technologies Inc NYSE A today announced that it will release financial results for the second quarter of fiscal year 2022 after the stock market closes on Tuesday May 24 The company will host a live webcast of its investor conference call in listenonly mode on the same day', 'link': 'https://finance.yahoo.com/news/agilent-announce-second-quarter-fiscal-150000331.html?.tsrc=rss', 'published': 'Tue, 26 Apr 2022 15:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-26 15:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,724 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Joins the National Institute for Innovation in Manufacturing to Advance Biomanufacturing', 'summary': 'SANTA CLARA Calif April 19 2022Agilent Technologies Inc NYSE A announced that it has joined the National Institute for Innovation in Manufacturing to Advance Biomanufacturing NIIMBL Membership in NIIMBL demonstrates Agilent’s commitment to supporting biopharma and biotherapeutics customer challenges through partnership and innovation using tools and workflows', 'link': 'https://finance.yahoo.com/news/agilent-joins-national-institute-innovation-120000496.html?.tsrc=rss', 'published': 'Tue, 19 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-19 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Joins the National Institute for Innovation in Manufacturing to Advance Biomanufacturing', 'summary': 'SANTA CLARA Calif April 19 2022Agilent Technologies Inc NYSE A announced that it has joined the National Institute for Innovation in Manufacturing to Advance Biomanufacturing NIIMBL Membership in NIIMBL demonstrates Agilent’s commitment to supporting biopharma and biotherapeutics customer challenges through partnership and innovation using tools and workflows', 'link': 'https://finance.yahoo.com/news/agilent-joins-national-institute-innovation-120000496.html?.tsrc=rss', 'published': 'Tue, 19 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-19 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,724 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Joins the National Institute for Innovation in Manufacturing to Advance Biomanufacturing', 'summary': 'SANTA CLARA Calif April 19 2022Agilent Technologies Inc NYSE A announced that it has joined the National Institute for Innovation in Manufacturing to Advance Biomanufacturing NIIMBL Membership in NIIMBL demonstrates Agilent’s commitment to supporting biopharma and biotherapeutics customer challenges through partnership and innovation using tools and workflows', 'link': 'https://finance.yahoo.com/news/agilent-joins-national-institute-innovation-120000496.html?.tsrc=rss', 'published': 'Tue, 19 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-19 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Joins the National Institute for Innovation in Manufacturing to Advance Biomanufacturing', 'summary': 'SANTA CLARA Calif April 19 2022Agilent Technologies Inc NYSE A announced that it has joined the National Institute for Innovation in Manufacturing to Advance Biomanufacturing NIIMBL Membership in NIIMBL demonstrates Agilent’s commitment to supporting biopharma and biotherapeutics customer challenges through partnership and innovation using tools and workflows', 'link': 'https://finance.yahoo.com/news/agilent-joins-national-institute-innovation-120000496.html?.tsrc=rss', 'published': 'Tue, 19 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-19 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,727 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Zacks Industry Outlook Highlights Agilent Technologies AMETEK Fortive and Cognex', 'summary': 'Agilent Technologies AMETEK Fortive and Cognex Zacks Industry Outlook article', 'link': 'https://finance.yahoo.com/news/zacks-industry-outlook-highlights-agilent-120812836.html?.tsrc=rss', 'published': 'Wed, 13 Apr 2022 12:08:12 +0000', 'ticker': 'A', 'Datetime': '2022-04-13 12:08:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Zacks Industry Outlook Highlights Agilent Technologies AMETEK Fortive and Cognex', 'summary': 'Agilent Technologies AMETEK Fortive and Cognex Zacks Industry Outlook article', 'link': 'https://finance.yahoo.com/news/zacks-industry-outlook-highlights-agilent-120812836.html?.tsrc=rss', 'published': 'Wed, 13 Apr 2022 12:08:12 +0000', 'ticker': 'A', 'Datetime': '2022-04-13 12:08:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,727 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Zacks Industry Outlook Highlights Agilent Technologies AMETEK Fortive and Cognex', 'summary': 'Agilent Technologies AMETEK Fortive and Cognex Zacks Industry Outlook article', 'link': 'https://finance.yahoo.com/news/zacks-industry-outlook-highlights-agilent-120812836.html?.tsrc=rss', 'published': 'Wed, 13 Apr 2022 12:08:12 +0000', 'ticker': 'A', 'Datetime': '2022-04-13 12:08:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Zacks Industry Outlook Highlights Agilent Technologies AMETEK Fortive and Cognex', 'summary': 'Agilent Technologies AMETEK Fortive and Cognex Zacks Industry Outlook article', 'link': 'https://finance.yahoo.com/news/zacks-industry-outlook-highlights-agilent-120812836.html?.tsrc=rss', 'published': 'Wed, 13 Apr 2022 12:08:12 +0000', 'ticker': 'A', 'Datetime': '2022-04-13 12:08:12'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,731 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': '4 Testing Equipment Stocks to Escape a Challenging Industry', 'summary': 'Coronavirusled disruptions are hurting the Zacks Electronics  Testing Equipment industry However industry participants like A AME FTV and CGNX are set to gain from 5G prospects', 'link': 'https://finance.yahoo.com/news/4-testing-equipment-stocks-escape-191407848.html?.tsrc=rss', 'published': 'Tue, 12 Apr 2022 19:14:07 +0000', 'ticker': 'A', 'Datetime': '2022-04-12 19:14:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': '4 Testing Equipment Stocks to Escape a Challenging Industry', 'summary': 'Coronavirusled disruptions are hurting the Zacks Electronics  Testing Equipment industry However industry participants like A AME FTV and CGNX are set to gain from 5G prospects', 'link': 'https://finance.yahoo.com/news/4-testing-equipment-stocks-escape-191407848.html?.tsrc=rss', 'published': 'Tue, 12 Apr 2022 19:14:07 +0000', 'ticker': 'A', 'Datetime': '2022-04-12 19:14:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,731 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': '4 Testing Equipment Stocks to Escape a Challenging Industry', 'summary': 'Coronavirusled disruptions are hurting the Zacks Electronics  Testing Equipment industry However industry participants like A AME FTV and CGNX are set to gain from 5G prospects', 'link': 'https://finance.yahoo.com/news/4-testing-equipment-stocks-escape-191407848.html?.tsrc=rss', 'published': 'Tue, 12 Apr 2022 19:14:07 +0000', 'ticker': 'A', 'Datetime': '2022-04-12 19:14:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': '4 Testing Equipment Stocks to Escape a Challenging Industry', 'summary': 'Coronavirusled disruptions are hurting the Zacks Electronics  Testing Equipment industry However industry participants like A AME FTV and CGNX are set to gain from 5G prospects', 'link': 'https://finance.yahoo.com/news/4-testing-equipment-stocks-escape-191407848.html?.tsrc=rss', 'published': 'Tue, 12 Apr 2022 19:14:07 +0000', 'ticker': 'A', 'Datetime': '2022-04-12 19:14:07'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,735 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Highlights Genomics and Cell Analysis Solutions for Cancer Research at AACR 2022', 'summary': 'SANTA CLARA Calif April 08 2022Agilent Technologies Inc NYSE A today announced cancer research innovations in cell analysis and genomics that will be on show at the American Association for Cancer Research Annual Meeting being held April 8  13 2022 in New Orleans Louisiana', 'link': 'https://finance.yahoo.com/news/agilent-highlights-genomics-cell-analysis-120000541.html?.tsrc=rss', 'published': 'Fri, 08 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-08 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Highlights Genomics and Cell Analysis Solutions for Cancer Research at AACR 2022', 'summary': 'SANTA CLARA Calif April 08 2022Agilent Technologies Inc NYSE A today announced cancer research innovations in cell analysis and genomics that will be on show at the American Association for Cancer Research Annual Meeting being held April 8  13 2022 in New Orleans Louisiana', 'link': 'https://finance.yahoo.com/news/agilent-highlights-genomics-cell-analysis-120000541.html?.tsrc=rss', 'published': 'Fri, 08 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-08 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,735 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Highlights Genomics and Cell Analysis Solutions for Cancer Research at AACR 2022', 'summary': 'SANTA CLARA Calif April 08 2022Agilent Technologies Inc NYSE A today announced cancer research innovations in cell analysis and genomics that will be on show at the American Association for Cancer Research Annual Meeting being held April 8  13 2022 in New Orleans Louisiana', 'link': 'https://finance.yahoo.com/news/agilent-highlights-genomics-cell-analysis-120000541.html?.tsrc=rss', 'published': 'Fri, 08 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-08 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Highlights Genomics and Cell Analysis Solutions for Cancer Research at AACR 2022', 'summary': 'SANTA CLARA Calif April 08 2022Agilent Technologies Inc NYSE A today announced cancer research innovations in cell analysis and genomics that will be on show at the American Association for Cancer Research Annual Meeting being held April 8  13 2022 in New Orleans Louisiana', 'link': 'https://finance.yahoo.com/news/agilent-highlights-genomics-cell-analysis-120000541.html?.tsrc=rss', 'published': 'Fri, 08 Apr 2022 12:00:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-08 12:00:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,739 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent A Boosts PDL1 IHC 288 pharmDX Use in European Union', 'summary': 'Agilent Technologies A boosts its presence in the companion diagnostics market by expanding the use of PDL1 IHC 288 pharmDx assay for esophageal squamous cell carcinoma treatment in the EU', 'link': 'https://finance.yahoo.com/news/agilent-boosts-pd-l1-ihc-151903069.html?.tsrc=rss', 'published': 'Thu, 07 Apr 2022 15:19:03 +0000', 'ticker': 'A', 'Datetime': '2022-04-07 15:19:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent A Boosts PDL1 IHC 288 pharmDX Use in European Union', 'summary': 'Agilent Technologies A boosts its presence in the companion diagnostics market by expanding the use of PDL1 IHC 288 pharmDx assay for esophageal squamous cell carcinoma treatment in the EU', 'link': 'https://finance.yahoo.com/news/agilent-boosts-pd-l1-ihc-151903069.html?.tsrc=rss', 'published': 'Thu, 07 Apr 2022 15:19:03 +0000', 'ticker': 'A', 'Datetime': '2022-04-07 15:19:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,739 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent A Boosts PDL1 IHC 288 pharmDX Use in European Union', 'summary': 'Agilent Technologies A boosts its presence in the companion diagnostics market by expanding the use of PDL1 IHC 288 pharmDx assay for esophageal squamous cell carcinoma treatment in the EU', 'link': 'https://finance.yahoo.com/news/agilent-boosts-pd-l1-ihc-151903069.html?.tsrc=rss', 'published': 'Thu, 07 Apr 2022 15:19:03 +0000', 'ticker': 'A', 'Datetime': '2022-04-07 15:19:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent A Boosts PDL1 IHC 288 pharmDX Use in European Union', 'summary': 'Agilent Technologies A boosts its presence in the companion diagnostics market by expanding the use of PDL1 IHC 288 pharmDx assay for esophageal squamous cell carcinoma treatment in the EU', 'link': 'https://finance.yahoo.com/news/agilent-boosts-pd-l1-ihc-151903069.html?.tsrc=rss', 'published': 'Thu, 07 Apr 2022 15:19:03 +0000', 'ticker': 'A', 'Datetime': '2022-04-07 15:19:03'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,743 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include MuscleInvasive Urothelial Carcinoma MIUC', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx immunohistochemical assay to extend the use of the test to patients diagnosed with muscleinvasive urothelial carcinoma MIUC who have tumor cell PDL1 expression ≥ 1 for adjuvant treatment with OPDIVO® nivolumab a PD1targeted immunotherapeutic from Bristol Myers Squibb', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-122500695.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:25:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:25:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include MuscleInvasive Urothelial Carcinoma MIUC', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx immunohistochemical assay to extend the use of the test to patients diagnosed with muscleinvasive urothelial carcinoma MIUC who have tumor cell PDL1 expression ≥ 1 for adjuvant treatment with OPDIVO® nivolumab a PD1targeted immunotherapeutic from Bristol Myers Squibb', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-122500695.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:25:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:25:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,743 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include MuscleInvasive Urothelial Carcinoma MIUC', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx immunohistochemical assay to extend the use of the test to patients diagnosed with muscleinvasive urothelial carcinoma MIUC who have tumor cell PDL1 expression ≥ 1 for adjuvant treatment with OPDIVO® nivolumab a PD1targeted immunotherapeutic from Bristol Myers Squibb', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-122500695.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:25:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:25:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include MuscleInvasive Urothelial Carcinoma MIUC', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx immunohistochemical assay to extend the use of the test to patients diagnosed with muscleinvasive urothelial carcinoma MIUC who have tumor cell PDL1 expression ≥ 1 for adjuvant treatment with OPDIVO® nivolumab a PD1targeted immunotherapeutic from Bristol Myers Squibb', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-122500695.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:25:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:25:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,747 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include Esophageal Squamous Cell Carcinoma', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced it has expanded CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx as an aid in identifying esophageal squamous cell carcinoma patients for treatment with Bristol Myers Squibb’s PD1targeted immunotherapeutic OPDIVO® nivolumab in combination with fluoropyrimidine and platinumbased chemotherapy or OPDIVO® in combination with YERVOY® ipilimumab These combined treatments provide new hop', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-121500724.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:15:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:15:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include Esophageal Squamous Cell Carcinoma', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced it has expanded CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx as an aid in identifying esophageal squamous cell carcinoma patients for treatment with Bristol Myers Squibb’s PD1targeted immunotherapeutic OPDIVO® nivolumab in combination with fluoropyrimidine and platinumbased chemotherapy or OPDIVO® in combination with YERVOY® ipilimumab These combined treatments provide new hop', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-121500724.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:15:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:15:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,747 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include Esophageal Squamous Cell Carcinoma', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced it has expanded CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx as an aid in identifying esophageal squamous cell carcinoma patients for treatment with Bristol Myers Squibb’s PD1targeted immunotherapeutic OPDIVO® nivolumab in combination with fluoropyrimidine and platinumbased chemotherapy or OPDIVO® in combination with YERVOY® ipilimumab These combined treatments provide new hop', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-121500724.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:15:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:15:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Agilent Companion Diagnostic Expands CEIVD Mark for PDL1 IHC 288 pharmDx to Include Esophageal Squamous Cell Carcinoma', 'summary': 'SANTA CLARA Calif April 05 2022Agilent Technologies Inc NYSE A today announced it has expanded CEIVD marking in the European Union for its PDL1 IHC 288 pharmDx as an aid in identifying esophageal squamous cell carcinoma patients for treatment with Bristol Myers Squibb’s PD1targeted immunotherapeutic OPDIVO® nivolumab in combination with fluoropyrimidine and platinumbased chemotherapy or OPDIVO® in combination with YERVOY® ipilimumab These combined treatments provide new hop', 'link': 'https://finance.yahoo.com/news/agilent-companion-diagnostic-expands-ce-121500724.html?.tsrc=rss', 'published': 'Tue, 05 Apr 2022 12:15:00 +0000', 'ticker': 'A', 'Datetime': '2022-04-05 12:15:00'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,751 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Why Savvy Investors Look For Ports In Storms Like Agilent Thermo Fisher And Others', 'summary': 'As supply chain constraints continue to squeeze health care stocks one analyst suggested Monday to look for ports in storms', 'link': 'https://finance.yahoo.com/m/ed970478-a7f1-390a-8d29-013d389edc51/why-savvy-investors-look-for.html?.tsrc=rss', 'published': 'Mon, 04 Apr 2022 20:10:02 +0000', 'ticker': 'A', 'Datetime': '2022-04-04 20:10:02'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Why Savvy Investors Look For Ports In Storms Like Agilent Thermo Fisher And Others', 'summary': 'As supply chain constraints continue to squeeze health care stocks one analyst suggested Monday to look for ports in storms', 'link': 'https://finance.yahoo.com/m/ed970478-a7f1-390a-8d29-013d389edc51/why-savvy-investors-look-for.html?.tsrc=rss', 'published': 'Mon, 04 Apr 2022 20:10:02 +0000', 'ticker': 'A', 'Datetime': '2022-04-04 20:10:02'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n",
      "> 2022-05-23 11:03:02,751 [error] Pushing error to error stream: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Why Savvy Investors Look For Ports In Storms Like Agilent Thermo Fisher And Others', 'summary': 'As supply chain constraints continue to squeeze health care stocks one analyst suggested Monday to look for ports in storms', 'link': 'https://finance.yahoo.com/m/ed970478-a7f1-390a-8d29-013d389edc51/why-savvy-investors-look-for.html?.tsrc=rss', 'published': 'Mon, 04 Apr 2022 20:10:02 +0000', 'ticker': 'A', 'Datetime': '2022-04-04 20:10:02'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "Traceback (most recent call last):\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 167, in _do_and_recover\n",
      "    return await self._do(event)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/storey/flow.py\", line 809, in _do\n",
      "    await self._handle_completed(event, completed)\n",
      "  File \"/User/.pythonlibs/jupyter-avia/lib/python3.7/site-packages/mlrun/serving/remote.py\", line 164, in _handle_completed\n",
      "    f\"For event {event}, RemoteStep {self.name} got an unexpected response \"\n",
      "ValueError: For event Event(id=2065940c97b147d38dced6310210e454-0000, key=['avia'], time=2022-05-23 11:02:54, body={'title': 'Why Savvy Investors Look For Ports In Storms Like Agilent Thermo Fisher And Others', 'summary': 'As supply chain constraints continue to squeeze health care stocks one analyst suggested Monday to look for ports in storms', 'link': 'https://finance.yahoo.com/m/ed970478-a7f1-390a-8d29-013d389edc51/why-savvy-investors-look-for.html?.tsrc=rss', 'published': 'Mon, 04 Apr 2022 20:10:02 +0000', 'ticker': 'A', 'Datetime': '2022-04-04 20:10:02'}), RemoteStep remote_scale got an unexpected response status 400: b'Exception: Expected key \"inputs\" in request body'\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: []\n",
       "Index: []"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# ingesting dummy (A MUST) \n",
    "import os\n",
    "import datetime\n",
    "\n",
    "name = os.environ['V3IO_USERNAME']\n",
    "now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "\n",
    "fstore.ingest(news_set,\n",
    "              pd.DataFrame.from_dict({'ticker':[name],\n",
    "                                      'Datetime': now,\n",
    "                                      'n_stocks':1}))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define the HTTP Source to_dictable the HTTP trigger on our function and expose the endpoint.\n",
    "# There is an option to declare key and timestamp inside the http source (here we dont send data through the http hence not needed)\n",
    "http_source = mlrun.datastore.sources.HttpSource()\n",
    "news_set.spec.source = http_source\n",
    "\n",
    "# code_to_function our mlrun wrapped function to deploy the ingestion pipeline on.\n",
    "# the serving runtimes enables the deployment of our feature set's computational graph\n",
    "function = mlrun.code_to_function(name='get_news',kind='serving',image='mlrun/mlrun', requirements=['yahoo_fin','graphviz'])\n",
    "function.spec.readiness_timeout=100000\n",
    "\n",
    "run_config = fstore.RunConfig(function=function, local=False).apply(mlrun.mount_v3io())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Deploying\n",
    "news_set_endpoint = fstore.deploy_ingestion_service(featureset=news_set, run_config=run_config)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Testing ingestion service"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "\n",
    "now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "\n",
    "t = requests.post(news_set_endpoint,json={'ticker':['news'],\n",
    "                                                 'Datetime': now,\n",
    "                                                 'n_stocks':4})\n",
    "t.text"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Creating scheduled mlrun job to invoke our function every time delta"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.makedirs('src',exist_ok=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile src/invoker.py\n",
    "\n",
    "import requests\n",
    "import datetime\n",
    "\n",
    "def ingestion_service_invoker(endpoint): \n",
    "    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "    \n",
    "    t = requests.post(endpoint,json={'ticker':['news'],\n",
    "                                     'Datetime': now,\n",
    "                                     'n_stocks':4})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# specifying '0 8 * * *' as schedule will trigger the function every day at 08:00 AM\n",
    "fn = mlrun.code_to_function(name='ingestion_service_news',kind='job',image='mlrun/mlrun',handler='ingestion_service_invoker', filename='src/invoker.py')\n",
    "fn.run(params={'endpoint':news_set_endpoint}, schedule='0 8 * * *')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
